# main_config.yaml

defaults:
    - retriever_config: retromae
    - reranker_config: null
    - generator_config: null
    - dataset_config: nq_open

run_name: ???
dataset_folder: 'datasets/'
index_folder: 'indexes/'
experiment_folder: 'experiments/'
processing_num_proc: 15
overwrite_datasets: false
debug: false

hydra:
    job:
        chdir: False
