# main_config.yaml

defaults:
    - _self_
    - retriever_config: retromae
    - reranker_config: null
    - generator_config: llama-2-7b-chat
    - dataset_config: nq_open

run_name: ???
dataset_folder: 'datasets/'
index_folder: 'indexes/'
run_folder: 'runs/'
experiment_folder: 'experiments/'
processing_num_proc: 40
overwrite_datasets: false
debug: false

hydra:
    job:
        chdir: False
